CREATE TABLE IF NOT EXISTS `person` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`adress` VARCHAR(200) NOT NULL,
	`firstName` VARCHAR(100) NOT NULL,
	`lastName` VARCHAR(100) NOT NULL,
	`gender` VARCHAR(80) NOT NULL,
	PRIMARY KEY (`id`)
);